#!/bin/bash
yum update
yum install nginx -y
yum install git -y
systemctl start nginx.service 
systemctl enable nginx.service
git clone https://github.com/viniciuscaol/portfolio.git
rm -rf /usr/share/nginx/html/
cp -rf portfolio/ /usr/share/nginx/html/